DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE media (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL, -- 'VIDEO' 또는 'AUDIO'
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL
);